[workspace]
members = [
    "crates/icn-cli",
    "crates/icn-node",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["ICN Developer Team"]
repository = "https://github.com/icn"
license = "MIT" 