# This is a template configuration file for local ICN node development
# ======================================================================

# Tendermint node configuration
[proxy_app]
laddr = "tcp://127.0.0.1:26658"

[moniker]
moniker = "local-dev-node"

[consensus]
timeout_commit = "1s"
skip_timeout_commit = false
create_empty_blocks = true
create_empty_blocks_interval = "5s"

[tx_index]
indexer = "kv"

[instrumentation]
prometheus = true
prometheus_listen_addr = ":26660"

[p2p]
laddr = "tcp://0.0.0.0:26656"
persistent_peers = ""
addr_book_strict = false
max_num_inbound_peers = 40
max_num_outbound_peers = 10

[rpc]
laddr = "tcp://0.0.0.0:26657"
cors_allowed_origins = ["*"]

# Application-specific configuration
[federation]
enabled = true

[storage]
enabled = true
path = "data/storage"

# Log levels: debug, info, warn, error
log_level = "info" 